#
###################################
# Site wide configuration
####################################
#
title: Palash Karmore
email: palashkarmore@gmail.com
description: A blog for my projects.
baseurl: ""
#url: https://palash247.github.io # the base hostname & protocol for your site
keywords: ["Machine Learning", "Artificial Intelligence", "Python", "Java", "Deep Learning"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          India/Delhi
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  # Line numbers in code block
  # syntax_highlighter_opts:
  #   block:
  #     line_numbers: true

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Palash Karmore
  avatar: palash-dp.jpg
  job: " Life | Software Engineering | Machine Learning | Python "
  bio: " Persuite of ikigai "
  email: palashkarmore@gmail.com
  disqus-shortname: palash247
  twitter: palashvk #username
  facebook: palash247
  google:
    plus: #username
    analytics: UA-56347465-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: palash247 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: palash-karmore #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
