title: Palash Karmore
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://palashkarmore.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /articles/:year-:month/:title
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  # - jekyll-archives
  - jekyll-sitemap

sass:
  style: compressed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

disqus:
  shortname: palash247

# Theme settings
theme_settings:
  default: system
  options:
    - light
    - dark
    - system

# Author information
author:
  name: Palash Karmore
  photo: /assets/images/profile.jpg
  bio: ""

# Social profiles
social:
  x: palashvk
  github: palash247
  linkedin: palash-karmore

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Archives
# jekyll-archives:
#   enabled:
#     - year
#     - month
#     - tags
#   layouts:
#     year: year-archive
#     month: month-archive
#     tag: tag-archive
#   permalinks:
#     year: '/:year/'
#     month: '/:year/:month/'
#     tag: '/tag/:name/'

